### ISSUE TITLE
Fix redirection

### ISSUE THREAD

**Issue by tpereira22** [PrinceSalatyell/minishell#18]
Fix redirection order. 

Redirection are working in general but it has some errors in the order the files appear in

**Comment by tpereira22** [comment]
Handle the '<>' '><' error.
Started to implement executable files in the current directory. Executables are working.

Next:
When './' and the name of a non-executable file (ex: text file), execve should execute the content of the file and not the file itself.
If file A has 'ls' in line 1, then when './A' execve has to execute 'ls' and not A.
if file A has 'ls' in line 1 and 'ls -l' in line 2, when './A' execve has to execute ls and then execute ls -l and any other command

Can't forget:
I forgot what I actually needed to fix in this issue and the discription doesn't help. Need to test in school again.

**Comment by PrinceSalatyell** [comment]
Link to PR:

https://github.com/PrinceSalatyell/minishell/pull/37

**Comment by PrinceSalatyell** [comment]
This has been merged
